[package]
name = "mocPolyWidget"
version = "0.1.0"
authors = ["ferry <alessandro.ferrari.2004@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
